"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)55(k=+k5oofe^4auy5(h0iwhr2(8-3#okwfjiu308lfag$ga='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["saragossa.pythonanywhere.com"]

STATIC_ROOT = BASE_DIR / 'staticfiles'
# Application definition
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
TAILWIND_APP_NAME = "theme"
INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'tailwind',
    'theme',
    'martor',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    ]
SITE_ID=1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'theme' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'


# --- Martor: maxed-out markdown editing (verified against martor 1.8.2) ---
# Theme choices: "bootstrap", "semantic", "tailwind".
# "bootstrap" keeps the editor self-contained inside the django admin.
MARTOR_THEME = 'bootstrap'

# Config feature keys take *string* booleans: "true"/"false".
#   emoji     -> emoji picker         imgur     -> image upload button
#   mention   -> @mentions            jquery    -> include jquery (django admin)
#   living    -> live preview updates spellcheck -> spellcheck underlines
#   hljs      -> highlight.js in the live preview
MARTOR_ENABLE_CONFIGS = {
    'emoji': 'true',
    'imgur': 'true',
    'mention': 'true',
    'jquery': 'true',
    'living': 'true',
    'spellcheck': 'true',
    'hljs': 'true',
}

# Valid button ids (from martor/bootstrap/toolbar.html):
#   bold italic horizontal heading pre-code blockquote unordered-list
#   ordered-list link image-link image-upload emoji direct-mention
#   toggle-maximize help
MARTOR_TOOLBAR_BUTTONS = [
    'bold', 'italic', 'horizontal', 'heading', 'pre-code',
    'blockquote', 'unordered-list', 'ordered-list', 'link',
    'image-link', 'image-upload', 'emoji', 'direct-mention',
    'toggle-maximize', 'help',
]

# Image upload goes to the real Imgur API. Add your own keys to enable it;
# without them the upload button returns a 401-style error.
MARTOR_IMGUR_CLIENT_ID = ''
MARTOR_IMGUR_API_KEY = ''

# Markdownify / upload endpoints are wired by main/urls.py at /martor/...
# (martor's own defaults are the same as these paths).
MARTOR_MARKDOWNIFY_URL = '/martor/markdownify/'
MARTOR_UPLOAD_URL = '/martor/uploader/'

# Martor's security extensions must be kept so |safe_markdown stays XSS-safe:
#   martor.extensions.escape_html handles the raw HTML passthrough.
MARTOR_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.extra',
    'markdown.extensions.nl2br',
    'markdown.extensions.smarty',
    'markdown.extensions.sane_lists',
    'markdown.extensions.toc',
    'markdown.extensions.attr_list',
    'markdown.extensions.admonition',
    # Martor built-in (urlize, whisper, emoji, video, XSS guard, ids)
    'martor.extensions.urlize',
    'martor.extensions.del_ins',
    'martor.extensions.mention',
    'martor.extensions.emoji',
    'martor.extensions.mdx_video',
    'martor.extensions.escape_html',
    'martor.extensions.mdx_add_id',
    # pymdownx extras (replaces fenced_code + codehilite with superfences)
    'pymdownx.tasklist',
    'pymdownx.superfences',
    'pymdownx.highlight',
    'pymdownx.magiclink',
    'pymdownx.tilde',
    'pymdownx.caret',
    'pymdownx.keys',
    'pymdownx.details',
    'mdx_math',
]

MARTOR_MARKDOWN_EXTENSION_CONFIGS = {
    'pymdownx.highlight': {
        'css_class': 'highlight',
        'use_pygments': True,
        'guess_lang': False,
        'linenums': False,
    },
    'mdx_math': {
        'enable_dollar_delimiter': True,
    },
}