# Generated by Django 6.0.2 on 2026-02-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('bulletin_author', models.CharField(default='cratis', max_length=5)),
            ],
        ),
    ]
