# Generated by Django 6.0.2 on 2026-02-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletins',
            old_name='bulletin_author',
            new_name='writeup_author',
        ),
        migrations.AddField(
            model_name='bulletins',
            name='title',
            field=models.CharField(default='title goes here.', max_length=20),
        ),
        migrations.AddField(
            model_name='bulletins',
            name='writeup_category',
            field=models.CharField(choices=[('WEB', 'web-apps'), ('RE', 'Reverse engineering'), ('SOC', 'Forensics')], default='SOC', max_length=3),
        ),
        migrations.AddField(
            model_name='bulletins',
            name='writeup_difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('I', 'Insane')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='bulletins',
            name='writeup_platform',
            field=models.CharField(choices=[('THM', 'TryHackMe'), ('PS', 'PortSwigger'), ('RM', 'Root-Me'), ('HTB', 'HackTheBox')], default='THM', max_length=3),
        ),
        migrations.AddField(
            model_name='bulletins',
            name='writeup_slug',
            field=models.SlugField(default='slugify', unique=True),
        ),
    ]
