# Generated by Django 6.0.2 on 2026-02-17 08:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_bulletin_author_bulletins_writeup_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletins',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
