# Generated by Django 6.0.2 on 2026-02-17 08:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bulletins_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletins',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
