# Generated by Django 6.0.1 on 2026-02-18 05:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bulletins_uuid_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('writeup_author', models.CharField(default='cratis', max_length=5)),
                ('title', models.CharField(default='title goes here.', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='bulletins',
            name='uuid_id',
        ),
    ]
