# Generated by Django 6.0.1 on 2026-02-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_intelnote_remove_bulletins_uuid_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletins",
            name="writeup_body",
            field=models.TextField(default="text"),
        ),
        migrations.AddField(
            model_name="bulletins",
            name="writeup_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="bulletins/%Y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="bulletins",
            name="title",
            field=models.CharField(default="ANALYSIS_LOG_0x0", max_length=100),
        ),
        migrations.AlterField(
            model_name="bulletins",
            name="writeup_author",
            field=models.CharField(default="cratis", max_length=20),
        ),
        migrations.AlterField(
            model_name="bulletins",
            name="writeup_slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
