# Generated by Django 5.1.3 on 2026-03-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_bulletins_writeup_body_bulletins_writeup_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletins",
            name="writeup_platform",
            field=models.CharField(
                choices=[
                    ("THM", "TryHackMe"),
                    ("PortSwigger", "PortSwigger"),
                    ("Root Me", "Root-Me"),
                    ("HTB", "HackTheBox"),
                ],
                default="THM",
                max_length=11,
            ),
        ),
    ]
