# Generated by Django 5.1.3 on 2026-05-24 11:37

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletins",
            name="writeup_body",
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name="bulletins",
            name="writeup_category",
            field=models.CharField(
                choices=[
                    ("WEB", "web-apps"),
                    ("RE", "Reverse engineering"),
                    ("SOC", "Forensics"),
                    ("SYS", "Systems"),
                ],
                default="SOC",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="bulletins",
            name="writeup_platform",
            field=models.CharField(
                choices=[
                    ("THM", "TryHackMe"),
                    ("PortSwigger", "PortSwigger"),
                    ("Root Me", "Root-Me"),
                    ("HTB", "HackTheBox"),
                    ("FAQ", "FAQ"),
                ],
                default="THM",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
