# Generated by Django 5.1.3 on 2026-05-24 12:02

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_bulletins_writeup_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletins",
            name="writeup_body",
            field=martor.models.MartorField(
                blank=True,
                help_text="Write your post content in Markdown",
                max_length=10000,
                null=True,
                verbose_name="Post Content",
            ),
        ),
    ]
